export const supabaseUrl = 'https://jewzptylhlqylgyuctuq.supabase.co'
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impld3pwdHlsaGxxeWxneXVjdHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4Nzc1NDksImV4cCI6MjA1ODQ1MzU0OX0.zsBhZB-j9IKsKmkfhn0lR0yvoHlWZTah-xGDYFWebfw'
